FROM node:24-alpine AS installer

WORKDIR /app

COPY package*.json ./

RUN npm install

FROM node:24-alpine AS tester

WORKDIR /app
COPY --from=installer /app/node_modules ./node_modules
COPY . .

RUN npm run test